  <script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false'></script>
  <script>var cord = [
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Biodiversity and conservation of Chihuahuan Desert invertebrates</h3>'+
        '</div>'+
    '<p><b>David&nbspBerg</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Roswell, NM </b><br>We are investigating the biodiversity and evolution of invertebrates in springs in the Chihuahuan Desert.  Many of these species are each limited to only one spring system.  Thus, each spring system contains its own unique biological community.  Because they occupy such small ranges and the water levels in many of these springs is declining due to pumping for irrigation, many of these species are in danger of extinction.</p>'+'</div>'+'</div>',33.394169,-104.522499],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Biodiversity and conservation of Chihuahuan Desert invertebrates</h3>'+
        '</div>'+
    '<p><b>David&nbspBerg</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Pecos River basin,</b><br>We are investigating the biodiversity and evolution of invertebrates in springs in the Chihuahuan Desert.  Many of these species are each limited to only one spring system.  Thus, each spring system contains its own unique biological community.  Because they occupy such small ranges and the water levels in many of these springs is declining due to pumping for irrigation, many of these species are in danger of extinction.</p>'+'</div>'+'</div>',30.451944,-101.732780],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Biodiversity and conservation of Chihuahuan Desert invertebrates</h3>'+
        '</div>'+
    '<p><b>David&nbspBerg</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Devils River, TX</b><br>We are investigating the biodiversity and evolution of invertebrates in springs in the Chihuahuan Desert.  Many of these species are each limited to only one spring system.  Thus, each spring system contains its own unique biological community.  Because they occupy such small ranges and the water levels in many of these springs is declining due to pumping for irrigation, many of these species are in danger of extinction.</p>'+'</div>'+'</div>',29.935278,-100.943054],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Biodiversity and conservation of Chihuahuan Desert invertebrates</h3>'+
        '</div>'+
    '<p><b>David&nbspBerg</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Laredo, TX</b><br>We are investigating the biodiversity and evolution of invertebrates in springs in the Chihuahuan Desert.  Many of these species are each limited to only one spring system.  Thus, each spring system contains its own unique biological community.  Because they occupy such small ranges and the water levels in many of these springs is declining due to pumping for irrigation, many of these species are in danger of extinction.</p>'+'</div>'+'</div>',27.506111,-99.507225],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Recycling of mine waste generated by Kyanite Mining Corporation in economically disadvantaged regions</h3>'+
        '</div>'+
    '<p><b>Mark&nbspKrekeler</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Dillwyn, Virginia </b><br>We have produced a series of three journal articles on mine waste generated by Kyanite Mining Corporation for the purpose of recycling the materials to improve the economically disadvantaged regions.     </p>'+'</div>'+'</div>',37.542927,-78.457222],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Recycling of mine waste generated by Kyanite Mining Corporation in economically disadvantaged regions</h3>'+
        '</div>'+
    '<p><b>Greg&nbspGeise</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Dillwyn, Virginia </b><br>We have produced a series of three journal articles on mine waste generated by Kyanite Mining Corporation for the purpose of recycling the materials to improve the economically disadvantaged regions.     </p>'+'</div>'+'</div>',37.542927,-78.457222],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Recycling of mine waste generated by Kyanite Mining Corporation in economically disadvantaged regions</h3>'+
        '</div>'+
    '<p><b>Erin&nbspLeGalley</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Dillwyn, Virginia </b><br>We have produced a series of three journal articles on mine waste generated by Kyanite Mining Corporation for the purpose of recycling the materials to improve the economically disadvantaged regions.     </p>'+'</div>'+'</div>',37.542927,-78.457222],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Recycling of mine waste generated by Kyanite Mining Corporation in economically disadvantaged regions</h3>'+
        '</div>'+
    '<p><b>William&nbspSchellenbach</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Dillwyn, Virginia </b><br>We have produced a series of three journal articles on mine waste generated by Kyanite Mining Corporation for the purpose of recycling the materials to improve the economically disadvantaged regions.     </p>'+'</div>'+'</div>',37.542927,-78.457222],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Construction of wetlands  for sewage pollution treatment</h3>'+
        '</div>'+
    '<p><b>Mark&nbspKrekeler</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Akumal, Quintana Roo </b><br>I have published several articles relating to constructed wetlands for the treatment of sewage pollution relating to this village and surrounding areas.   </p>'+'</div>'+'</div>',20.395975,-87.316872],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Construction of wetlands  for sewage pollution treatment</h3>'+
        '</div>'+
    '<p><b>Clancy&nbspCalkins</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Akumal, Quintana Roo </b><br>I have published several articles relating to constructed wetlands for the treatment of sewage pollution relating to this village and surrounding areas.   </p>'+'</div>'+'</div>',20.395975,-87.316872],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Construction of wetlands  for sewage pollution treatment</h3>'+
        '</div>'+
    '<p><b>Olaf&nbspBorkiewicz</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Akumal, Quintana Roo </b><br>I have published several articles relating to constructed wetlands for the treatment of sewage pollution relating to this village and surrounding areas.   </p>'+'</div>'+'</div>',20.395975,-87.316872],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Exploration of Blackhand sandstone in regard to sea level decrease </h3>'+
        '</div>'+
    '<p><b>Mark&nbspKrekeler</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Hocking Hills State Park, OH</b><br>We run regular field trips as part of my introductory geology classes at the Hamilton Campus.  We explore the Blackhand sandstone in the region which reflects a 60 meter sea level drop approximately 330 Million years ago.  </p>'+'</div>'+'</div>',39.445049,-82.510864],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Exploration of glacial grooves and landforms</h3>'+
        '</div>'+
    '<p><b>Mark&nbspKrekeler</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Kelley</b><br>We ran a field trip to this park in December 2010 to explore glacial grooves and landforms.  </p>'+'</div>'+'</div>',41.527802,-82.713615],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Analysis of coal geology</h3>'+
        '</div>'+
    '<p><b>Mark&nbspKrekeler</b>,&nbspGeology</p>','<div id="bodyContent">'+
    '<p><b>Vancleve , Kentucky</b><br>We run field trips to this area to study the coal geology of the region.  Sites include major coals seams, earthquake deformed sediment, ancient rivers, and a 312 million year old volcanic ash layer.  We also see sites relating to mountain top removal, underground coal fires and mine drainage problems.</p>'+'</div>'+'</div>',37.627590,-83.413513],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Impact of abiotic drives on protest trophic strategy in Antarctic lakes</h3>'+
        '</div>'+
    '<p><b>Rachael&nbspMorgan-Kiss</b>,&nbspMicrobiology</p>','<div id="bodyContent">'+
    '<p><b>McMurdo Dry Valleys, Antarctic</b><br>This research project will focus on single-celled microorganisms called </p>'+'</div>'+'</div>',-77.733330,162.166672],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Ecological and ethnobotanical research at Mt. Kasigau</h3>'+
        '</div>'+
    '<p><b>Kim&nbspMedley</b>,&nbspGeography</p>','<div id="bodyContent">'+
    '<p><b>Mt. Kasigau, Kenya</b><br>Our study builds from ecological and ethnobotanical research at Mt. Kasigau, Southeastern Kenya, where there is a steep gradient in seasonal forest change from deciduous Acacia-Commiphora bushland, through mixed montane woodlands, and to evergreen forest. The overall research thesis is that local, short-term analyses of biophysical changes in plant communities across this ecologically complex landscape should provide a sensitive indicator of livelihood conditions that correspond with dynamic changes in human-resource adaptive capacities. The study focuses on the extraction of woody plant products as one important resource entitlement and relates use practices with ecological patterns of diversity in vegetation types and biophysical dynamics</p>'+'</div>'+'</div>',-3.816667,38.666668],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Ecological and ethnobotanical research at Mt. Kasigau</h3>'+
        '</div>'+
    '<p><b>John&nbspMaingi</b>,&nbspGeography</p>','<div id="bodyContent">'+
    '<p><b>Mt. Kasigau, Kenya</b><br>Our study builds from ecological and ethnobotanical research at Mt. Kasigau, Southeastern Kenya, where there is a steep gradient in seasonal forest change from deciduous Acacia-Commiphora bushland, through mixed montane woodlands, and to evergreen forest. The overall research thesis is that local, short-term analyses of biophysical changes in plant communities across this ecologically complex landscape should provide a sensitive indicator of livelihood conditions that correspond with dynamic changes in human-resource adaptive capacities. The study focuses on the extraction of woody plant products as one important resource entitlement and relates use practices with ecological patterns of diversity in vegetation types and biophysical dynamics</p>'+'</div>'+'</div>',-3.816667,38.666668],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Seed dispersal, tree regeneration, and sustainability in the strip clear-cutting system of forest management for timber production in the Peruvian Amazon</h3>'+
        '</div>'+
    '<p><b>David&nbspGorchov</b>,&nbspBotany</p>','<div id="bodyContent">'+
    '<p><b>Peru/Loreto</b><br>We have been studying the regeneration of tropical rain forest following logging by </p>'+'</div>'+'</div>',-4.916667,-73.666664],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Influence of watersheds and fish on the ecology and water quality of Ohio</h3>'+
        '</div>'+
    '<p><b>Michael J.&nbspVanni</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Ohio</b><br>We are investigating the influence of watersheds and fish on the ecology and water quality of Ohio</p>'+'</div>'+'</div>',39.961174,-82.998795],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading"> Physiological Mechanisms in Anuran Adaptation to Extreme Cold</h3>'+
        '</div>'+
    '<p><b>Jon&nbspCostanzo</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Fairbanks, AK</b><br>Owing to its high dispersal ability, broad geographic range, and extreme northern distribution (into the Arctic Circle), the wood frog, Rana sylvatica, is a valuable species in studies of environmental adaptation. Our research follows from preliminary findings that the lower thermal limit of freezing survival in a R. sylvatica population near the northern limit of the species</p>'+'</div>'+'</div>',64.837776,-147.716385],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Effect of tilapia on plankton communities and nutrients in tropical lakes</h3>'+
        '</div>'+
    '<p><b>Michael J.&nbspVanni</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Brazil</b><br>We are investigating the effects of tilapia, an omnivorous fish, on plankton communities and nutrients in tropical lakes. Tilapia is native to Africa but has been introduced into many tropical and subtropical lakes, including widespread introductions in Brazil. There is concern about the effects of this invasive species on native communities.</p>'+'</div>'+'</div>',-14.235003,-51.925282],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Freezing and Dehydration Tolerance in an Antarctic Insect</h3>'+
        '</div>'+
    '<p><b>Richard E.&nbspLee Jr.</b>,&nbspZoology</p>','<div id="bodyContent">'+
    '<p><b>Palmer Station, Antarctic Peni</b><br>Polar terrestrial environments are often described as deserts, where water availability is a critical factor limiting the distribution of terrestrial organisms. The midge, Belgica antarctica, is the southernmost free-living terrestrial insect. This extremophilic species and its location on the Antarctic Peninsula provide an excellent model system for investigating mechanisms of stress tolerance and the role of extreme photoperiodic changes in coordinating these seasonal adaptations.  Specifically, we will use gene and protein level approaches to investigate the seasonal roles of dehydration and photoperiodic cues in preparing a polar insect for winter survival.</p>'+'</div>'+'</div>',-64.749580,-64.052101],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Investigation of patients with chronic illness conditions</h3>'+
        '</div>'+
    '<p><b>Cameron&nbspHay-Rollins</b>,&nbspAnthropology</p>','<div id="bodyContent">'+
    '<p><b>Los Angeles, CA</b><br>  We are investigating the knowledge access, illness experience, and clinical interactions of patients with chronic illness conditions (2003-present).</p>'+'</div>'+'</div>',34.052235,-118.243683],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Anthropological fieldwork among the Sasak people </h3>'+
        '</div>'+
    '<p><b>Cameron&nbspHay-Rollins</b>,&nbspAnthropology</p>','<div id="bodyContent">'+
    '<p><b>Lombok, Indonesia</b><br>I conducted anthropological fieldwork among the Sasak people to understand their ethnomedical practices within a broader context of poverty (1993-1995), and continue to analyze the data from that study.</p>'+'</div>'+'</div>',-8.650978,116.324944],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Images of Humanity</h3>'+
        '</div>'+
    '<p><b>Cameron&nbspHay-Rollins</b>,&nbspAnthropology</p>','<div id="bodyContent">'+
    '<p><b>European Union Countries</b><br>Students of ATH 335L created a visual project called Images of Humanity to update Edward Steichen</p>'+'</div>'+'</div>',48.856613,2.352222],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Development of Educational and Community Uses for Talawanda High School Natural Areas</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio</b><br>The Talawanda School District in Butler County, Ohio, is building a new high school on a 147 acre plot of land.  When completed the building, parking areas and sports fields of the new high school will occupy 50 acres, but the remaining 97 acres are comprised of agricultural, natural, and restored habitats.  These natural and restored lands provide an exceptional opportunity for ecological and agricultural education. A team of graduate students from Miami University</p>'+'</div>'+'</div>',39.486683,-84.728760],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Using Community-Based Social Marketing to Foster Sustainable Agricultural Practices in Clermont County, Ohio</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Clermont County, Ohio</b><br>The East Fork of the Little Miami River Watershed in Clermont County, Ohio, which encompasses nearly 320,000 acres in Southwestern Ohio, has been reported to have more than 70% of its land usage devoted row crop agriculture. Without adequate management practices, row crop agriculture can contribute to declining water quality and biological integrity. This is especially a concern in Clermont County because the East Fork flows into Harsha Lake, a primary source of drinking water for 100,000 residents.  The East Fork Watershed Collaborative has been working since 2001 to restore and enhance water quality in the East Fork Little Miami Watershed. Despite these efforts, the adoption of sustainable agricultural practices is not sufficient to reach water quality goals in the watershed. To understand why few producers have adopted sustainable practices, a team of graduate students from Miami University</p>'+'</div>'+'</div>',39.077129,-84.179192],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Development of a Park Master Plan and Park Site Development Plan for Union County, Indiana</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Union County, Indiana</b><br>The park system in Union County, Indiana, includes several sports fields, but lacks an admission-free community park with picnic areas, hiking trails, a space for outdoor cultural events, and other passive recreation. The Union County Parks and Recreation Board (UCPRB) has recently acquired 15 acres of land in the town of Liberty and needs a Site Development Plan. As part of a Professional Service Project, a team of graduate students from Miami University</p>'+'</div>'+'</div>',39.635563,-84.931000],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Managing Storm Water Runoff</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Clermont County, Ohio</b><br>The goal of this project was to identify the barriers associated with residents implementing on-site best management practices (BMPs), such as rain barrels and rain gardens.</p>'+'</div>'+'</div>',39.085949,-84.180405],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Assessing Ohio</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Ohio</b><br>Analyze the quality of Ohio</p>'+'</div>'+'</div>',40.417286,-82.907120],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Erosion Control in Bull Run</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Bull Run, Oxford, Ohio</b><br>Identify possible sustainable storm water management options that would reduce runoff and erosion along Bull Run. </p>'+'</div>'+'</div>',39.503201,-84.759186],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Warren County Energy Conservation</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Warren County Ohio</b><br>The goal of this project was to determine if a position should be created to address energy conservation interests of the citizens.</p>'+'</div>'+'</div>',39.424141,-84.185715],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Low Impact Development in Oxford</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio</b><br>A feasibility analysis of various zoning codes with consideration of political, geological, and climatic context of Oxford.  </p>'+'</div>'+'</div>',39.509556,-84.744659],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Crawford House and Woods Demonstration Site</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Hamilton, Ohio</b><br>Develop the historic Crawford House and Woods to be a local demonstration site for environmental stewardship.   </p>'+'</div>'+'</div>',39.398983,-84.562538],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Tree Inventory and Carbon Sequestration Estimation</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio</b><br>Assess the carbon sequestration potential of the city-owned trees and to provide recommendations on how to maximize the benefit of urban trees.</p>'+'</div>'+'</div>',39.510731,-84.742104],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Historical Wetland Education</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Preble County, Ohio</b><br>Create a wetland education program for the Preble County Historical Society.</p>'+'</div>'+'</div>',39.777824,-84.689751],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Presence/Absence of Bobcat (Lynx rufus) and an Assessment of the Relative Abundance ofMammals in Hueston Woods State Park</h3>'+
        '</div>'+
    '<p><b>Matt&nbspHallett</b>,&nbspEnvironmental Science (IES)</p>','<div id="bodyContent">'+
    '<p><b>College Corner, Ohio</b><br>Animals will be observed through passive capture_recapture techniques using motion censored cameratraps in this project. The bobcat (Lynx rufus) is the focus of this project, as bobcat populations havebeen recovering over the last decade, but they have not been documented in Hueston Woods StatePark for decades. Hueston Woods staff have expressed interest in understanding whether or notbobcats are utilizing this habitat so that they can adjust their management of the area accordingly.Previous studies have shown camera traps to be an excellent tool for determining thepresence/absence of rare species as they do not require human presence, can be placed inpreferred habitat areas and can operate 24 hours a day. Additional species captured on cameratraps will also be quantified in terms habitat occupancy, diversity and relative abundance. Specieswhere individual animals can be identified via unique patterns or other defining characteristics couldalso allow for estimates of population size and density, activity and spatial distribution. On anecosystem level, all of these measures can be used to evaluate ecosystem health and suitability ofhabitat for target species like bobcats. These measures can help inform the management of ahabitat area like Hueston Woods as a refuge or corridor for wildlife in a highly fragmented,agriculture dominated landscape.</p>'+'</div>'+'</div>',39.569859,-84.737679],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Control of Energetics: the Catbird Annual Cycle</h3>'+
        '</div>'+
    '<p><b>Paul&nbspSchaeffer</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Ecological Resea</b><br>Migratory birds undertake one of nature</p>'+'</div>'+'</div>',39.528721,-84.722717],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Genetic diversity and population biology of small mammals in the Great Lakes region</h3>'+
        '</div>'+
    '<p><b>Susan&nbspHoffman</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Michigian</b><br>Two species of mice, the white-footed mouse Peromyscus leucopus (Pln) and the deer mouse Peromyscusmaniculatus, are morphologically very similar and have been found to share an ecological role in many areas ofNorth America (Wolff 1985). Prior to about 1980, the subspecies Peromyscus maniculatus gracilis (Pmg) occupiedthe Upper Peninsula and northern half of the Lower Peninsula of Michigan, whereas Pln occupied only the LowerPeninsula (Baker 1983). During the last 30-40 years, however, Pmg has disappeared from the southern part of itsrange in the Great Lakes region (Myers et al. 2009), while Pln has moved further north and east. Pmg is still foundthroughout the Upper Peninsula of Michigan, but only a few small populations remain in the Lower Peninsula.Evidence from a number of studies indicates that Pmg is better adapted to cold than is Pln (e.g. Pierce and Vogt1993). Because Pln seems to have a greater sensitivity to low temperatures than Pmg, Pmg is expected to dominatewhen winters are long and severe; this differential response to winter temperatures is believed to have set thehistorical boundaries between the ranges of the two kinds of mice. Data collected at weather stations over the lastcentury demonstrate that winters in Michigan have been ending progressively earlier over the last 80 years, and thataverage temperatures are rising (Myers et al. 2009). These changes in the length of winters in the Great Lakesregion may be affecting the relative densities of the Peromyscus populations, enabling Pln to spread northwards andto either actively or passively replace Pmg (Myers et al. 2009).The primary purpose of this project is to study the genetic variability and population ecology of the Peromyscuspopulations involved in this displacement event. We are interested in comparing the levels of variability within theremaining small Pmg populations in the Lower Peninsula of Michigan to variability in the populations of the easternUpper Peninsula and also to the variability in extinct populations, as represented by museum specimens. The small,isolated populations of Pmg in the Lower Peninsula are likely to be more vulnerable to inbreeding and genetic driftthan the larger, more continuous populations in Northern Michigan (Vucetich et al. 2001). If the pockets of Pmg inthe Lower Peninsula are isolated from each other by the presence of Pln and/or by unsuitable habitat, then thejuveniles will be unable to disperse, leading to inbreeding (Bataillon and Kirkpatrick 2000). Also, such isolatedpopulations are subject to genetic drift, which is a loss of alleles due to random loss of the individuals that bearthem as the populations become smaller (Taylor and Hoffman 2010). Such losses of variability are known to haveoccurred in other species, but are usually not measured until after the losses have happened (Amos and Harwood1998; Finke and Jetschke 1999). The remnant populations of Pmg can serve as a particularly good model systemfor studying the genetic effects of isolation as that isolation progresses.We are also interesting in studying whether the genetic structure and phenotypic plasticity of the newlyestablished populations of Pln in areas that until recently contained only Pmg are significantly different frompopulations from the </p>'+'</div>'+'</div>',43.137115,-84.968559],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Abnormal Behavior in Captive Primates at the Cincinnati Zoo</h3>'+
        '</div>'+
    '<p><b>Scott&nbspSuarez</b>,&nbspATH</p>','<div id="bodyContent">'+
    '<p><b>Cincinnati Zoo</b><br>For more than 50 years, students of animal behavior have been concerned about the effects of artificialhousuing on the behavior of captive animals. Consequently, the US Government passed the AnimalWelfare Act in order to mandate that those housing captive animals must make efforts to improvethe psychological well_being of captive animals. Psychological well_being is typically measured intwo broad ways: captive animals should demonstrate a full_range of species_typical behaviors, andcaptive animals should be free of deleterious, stereotypical behaviors. All zoos make concertedefforts to provide for psychological well_being, from placing animals in naturalistic habitats andnaturalistic social groupings, meant to provide the animals with opportunities to engage in speciestypicalbehaviors, to providing activities and challenges to animals meant to occupy time andattention and therefore reduce species_atypical behaviors. The Cincinnati Zoo does provides all ofthese to captive primates. This project will assess the effectiveness of these efforts by examiningthe behavior of several groups of captive primates, comparing social grouping patterns, housingcondition, and environmental enrichment.</p>'+'</div>'+'</div>',39.145271,-84.508018],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Four Mile Creek Watershed Inventory</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Four Mile Creek Watershed</b><br>A watershed is a geographical area, characterized by the drainage of surface water into a common outlet, such as a stream, river, or lake (1). The Clean Water Act of 1972 led to the Watershed Approach, which determines the quality of the water resource by examining environmental indicators of the entire watershed through Watershed Action Plans (WAP) (1).WAPs have identified many of the known sources of pollution, such as discharge from industries and wastewater treatment plants. However, habitat degradation and nonpoint sources of pollution account for most of the nation</p>'+'</div>'+'</div>',39.598244,-84.742073],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Updating Miami University</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>In April 2011, President David Hodge unveiled Miami</p>'+'</div>'+'</div>',39.508640,-84.733299],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Hueston Woods State Park Bikeway Feasibility Study</h3>'+
        '</div>'+
    '<p><b>Suzanne&nbspZazycki</b>,&nbspInstitute for the Environment </p>','<div id="bodyContent">'+
    '<p><b>Hueston Woods State Park</b><br>Hueston Woods State Park is one of the top five most visited parks in Ohio. Its 3,000 acres are visited by about 2.5 million people each year. Its natural areas support wildlife preservation and offer opportunities for a number of recreational activities. There are more than 46 miles of hiking, cycling and equestrian trails in the park. However, there is no trail along the Main Loop Road, the primary route of travel throughout the park.</p>'+'</div>'+'</div>',39.571892,-84.735107],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Neurobiological mechanisms of recent and remote fear memories</h3>'+
        '</div>'+
    '<p><b>Jennifer&nbspQuinn</b>,&nbspPSY</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>The proposed experiments address a role for dorsal hippocampus (DH), ventral hippocampus (VH) and prefrontalcortex (PFC) in the acquisition, consolidation, expression, and reconsolidation of long-term fear memories. TheHPC and PFC differentially contribute to fear learning about places (contexts) and specific environmental cues(discrete stimuli). Further, the involvement of these two brain regions in fear learning depend upon the way inwhich discrete stimuli are presented. Most recently, a number of reports have indicated that the HPC contributesto the consolidation of fear memories over time such that its involvement dissipates with time following a fearlearning event. By contrast, the contribution of the PFC increases with time following the fear learning event. Ithas been suggested that the PFC serves as a permanent storage site for fear memories that are initiallyhippocampus-dependent. However, investigations of this potential HPC-PFC interaction in the storage of longtermfear memories are in their infancy. The proposed studies aim to define the conditions under which these twobrain regions (independently and interactively) are required for fear memory retrieval, with an emphasis on HPCand mPFC subregions.</p>'+'</div>'+'</div>',39.511841,-84.731392],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Fish as sinks and sources of nutrients in freshwater ecosystems</h3>'+
        '</div>'+
    '<p><b>Michael&nbsp Vanni</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>Fish play important roles in the nutrient cycles of freshwater food webs through several mechanisms, such as nutrientregeneration, translocation of nutrients within and among ecosystems, and indirect influences on nutrient cyclesvia cascading trophic interactions. Direct and indirect effects of fish can supply nutrients to primary producers atrates comparable to major nutrient sources, such as external nutrient loadings.Fish can be both sinks and sources of nutrients in lakes; however, most studies dealing with the </p>'+'</div>'+'</div>',39.511017,-84.731308],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Phenotypic plasticity of energetic capacity in migratory birds.</h3>'+
        '</div>'+
    '<p><b>Paul&nbspSchaeffer</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Northern, Michigan</b><br>Building on previous work in our laboratory, this study will compare the maximal capacity for energy use of free-living songbirds at their tropical winter homes (in Panama), their summer breeding grounds in (North America, including Ohio) and during migration through the Oxford area. We will measure summit metabolism of all birds studied to quantify metabolic capacity and release all animals after measurements are completed. The hypothesis being examined is that migrant bird species have much higher capacity for energy use while migrating or breeding at northern latitudes than while overwintering at tropical latitudes. Thus rather than evolved life history differences, phenotypic plasticity determines the ranges of metabolic activity observed in previous studies of temperate and tropical birds. For this proposal, we will measure maximal metabolic rate of wild birds at field sites in Northern Michigan.</p>'+'</div>'+'</div>',44.490108,-84.529434],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">In vivo stimulation of BAT by Adenovirus directed HB-EGF and ADAM 12S</h3>'+
        '</div>'+
    '<p><b>Paul&nbspHarding</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>Our laboratory has previously demonstrated that in vitro co-expression of heparin-binding EGF-like growth factor(HB-EGF) and a disintegrase and metalloprotease (ADAM) 12S stimulates transdifferentiation of cells into brownadipose tissue (BAT) using a number of cell lines including, mouse fibroblasts, epidermoid carcionoma cells,human embryonic kindey cells, etc. The purpose of this study is to demonstrate whether co-expression of HBEGFand ADAM 12S in vivo using adenoviral vectors are capable stimulating BAT.</p>'+'</div>'+'</div>',39.511082,-84.731461],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Spatiotemporally-Controlled Keatin Biomaterial Delivery System for Functional Tissue Regeneration</h3>'+
        '</div>'+
    '<p><b>Justin&nbspSaul</b>,&nbspCPE</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>Traumatic injuries in civilian and military populations as a result of high energy impacts commonly damage multiple types of tissue including skin, bone, and muscle. Of these injuries, muscle is arguably the most difficult to repair. Although there are some surgical techniques for autologous muscle repair, the methods are technically challenging, give less-than-desirable results, and lead to defects at the donor site (donor sige morbidity). Unlike skin and bone, there ae currently no tissue engineered products commercially available to aid physicians in repair of these types of injuries without autologous tissues. Methods in which cells, rather than whole tissues, could be delivered to sites of injury offer the potential to aid in repair and regeneration. Finding suitable materials that can support cell survival and allow cell delivery in a minimally-invasive fashion is an important aspect of this effort. Towards this end, we have been investigating a material called keratin that is extracted from human hair. This material supports muscle cell survival and can be delivered in a minimally-invasive way. The goal of the proposed study is to determine if cells that promote muscle tissue formation/regeneration can be incorporated into keratin and if the material can be placed into a muscle defect, remain at the site of implantation (through adhesion to the existing tissue), and support formation of primitive muscle tissue. </p>'+'</div>'+'</div>',39.511082,-84.731461],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">The role of ultraviolet radiation in the diel vertical migration of Daphnia and Copepoda across spatial and tempoal transparency gradients </h3>'+
        '</div>'+
    '<p><b>Craig&nbspWilliamson</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Pennsylvania </b><br>The proposed research will investigate the relative roles of ultraviolet radiation, visual predation pressure, temperature and algal resource availability on the diel vertical migration(DVM) of pelagic zooplankton in freshwater lakes. Visual predation has long been put forth as the ultimate explanation for DVM behavior of zooplankton but other research suggests that damage from ultraviolet radiation may also be an important drivers of this behavior. Williamson et al (2011) posited the Transparency-Regulator hypothesis that provides a framework for assessing the relative roles of each of these four drivers in systems of varying transparency. The goal of this project is to test the Transparency-Regulator hypothesis and quantify the strenght of each of the biotic and abiotic factors that drive DVM across systems of varying transparencies. One of the primary biotic factors involved in driving DVM behavior of zooplankton is the presence and abundance of planktivorous fish. To assess the role of visual predation in driving DVM behavior, measurements of the planktivouous fish population abundances and species compositions are necessary. We propose using trapping efforts to quanity visual predation pressure in out study systems. </p>'+'</div>'+'</div>',41.381870,-75.292381],
      ['<div id="content">'+
    '<div id="siteNotice">'+
    '<h3 id="firstHeading" class="firstHeading">Thermal acclimatization in Green frog tadpoles.</h3>'+
        '</div>'+
    '<p><b>Paul&nbspSchaeffer</b>,&nbspZOO</p>','<div id="bodyContent">'+
    '<p><b>Oxford, Ohio (Miami University</b><br>Rana clamitans (green frogs) are commonly found distributed throughout the Eastern and Midwestern United States, and in Southeastern Canada. Adults hibernate during the winter (beginning in mid-October and emerging at the end of March), in the bottoms of streams, in the mud or on land under some form of covering. The breeding season for R. clamitans begins in May and lasts until mid-August. After the eggs are laid, embryonic development to hatching takes place in about a week. After hatching, the green frog tadpoles can take up to a year to completely metamorphose and become sexually mature, which requires that tadpoles over-winter in ponds.Acclimatization is the reversible and seasonal process of adjusting physiological parameters to benefit animal performance and promote survival. Acclimatization differs from adaptation in that adaptation is an evolutionary process that occurs over multiple generations where as acclimation transpires during an animal</p>'+'</div>'+'</div>',39.510944,-84.731148],];function initialize() {
    var latlng = new google.maps.LatLng(43.92, -80.25);
    var myOptions = {
        zoom: 3,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    };
    var map = new google.maps.Map(document.getElementById('map_canvas'),myOptions);
    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < cord.length; i++) {  
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(cord[i][2], cord[i][3]),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(cord[i][0]);
                infowindow.open(map, marker);
                document.getElementById('abstract').innerHTML=(cord[i][1]);

            }
        })(marker, i));
    }
}
</script><script>

var t = document.getElementsByTagName("controls");
t.addEventListener("touchstart", handleStart, false);

function zoomLocal() {
    var latlng = new google.maps.LatLng(39.50872222, -84.73271389);
    var myOptions = {
        zoom: 15,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    };
    var map = new google.maps.Map(document.getElementById('map_canvas'),myOptions);
    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < cord.length; i++) {  
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(cord[i][2], cord[i][3]),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(cord[i][0]);
                infowindow.open(map, marker);
                document.getElementById("abstract").innerHTML=(cord[i][1]);

            }
        })(marker, i));
    }
}

function zoomRegional() {
    var latlng = new google.maps.LatLng(39.20872222, -84.03271389);
    var myOptions = {
        zoom: 8,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    };
    var map = new google.maps.Map(document.getElementById('map_canvas'),myOptions);
    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < cord.length; i++) {  
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(cord[i][2], cord[i][3]),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(cord[i][0]);
                infowindow.open(map, marker);
                document.getElementById("abstract").innerHTML=(cord[i][1]);

            }
        })(marker, i));
    }
}
function zoomNational() {
    var latlng = new google.maps.LatLng(38.92, -90.25);
    var myOptions = {
        zoom: 5,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    };
    var map = new google.maps.Map(document.getElementById('map_canvas'),myOptions);
    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < cord.length; i++) {  
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(cord[i][2], cord[i][3]),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(cord[i][0]);
                infowindow.open(map, marker);
                document.getElementById("abstract").innerHTML=(cord[i][1]);

            }
        })(marker, i));
    }
}
function zoomInternational() {
    var latlng = new google.maps.LatLng(25.92, -10.25);
    var myOptions = {
        zoom: 3,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    };
    var map = new google.maps.Map(document.getElementById('map_canvas'),myOptions);
    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < cord.length; i++) {  
        marker = new google.maps.Marker({
            position: new google.maps.LatLng(cord[i][2], cord[i][3]),
            map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(cord[i][0]);
                infowindow.open(map, marker);
                document.getElementById("abstract").innerHTML=(cord[i][1]);

            }
        })(marker, i));
    }
}
</script>

<style>
#abstract{
  padding: 1%;
  font-size: 20px;
  text-align:left;
  position:left 70%;
  max-height: 20%;
  min-height: 20%;
  overflow: scroll;
}
#map_canvas{
    width:100%;
    height:500px;
    padding-top: 5px;
    box-shadow:0px 0px 4px 3px rgba(68,85,102,0.9);
}

</style>

<div class="container">
  <div class="page-header">
  <img class="pull-right" src="files/img/social-media-icon-large.png" />
  <h1>Miami University Research Efforts Around the World</h1>
  </div>
<div id="map_canvas" class="img-polaroid"></div>

<div id="abstract"></div>
</div>
